### ISSUE TITLE
Should ignoring the `FrameTypeError` be OK?

### ISSUE THREAD

**Issue by belltoy** [nsqio/libnsq#7]
I notice that libnsq just ignore the `FrameTypeError`. Should it be OK?

In my case, I cache some messages received and handle them a little later, but if it take more time before sending back finish command than the nsqd option `msg_timeout`, the finish command would be failed. I think we should need to know the error response from nsqd.

[code here](https://github.com/nsqio/libnsq/blob/master/nsqd_connection.c#L60-L74)

**Comment by mreiferson** [comment]
@belltoy good point, it should probably provide a callback to receive errors in user code?

**Comment by belltoy** [comment]
According to the [A Brief Interlude on Errors](http://nsq.io/clients/building_client_libraries.html#a-brief-interlude-on-errors), nsqd will forcibly close the connection, except `E_FIN_FAILED` `E_REQ_FAILED ` `E_TOUCH_FAILED `.

And in my case, it is user code's responsibility to avoid message timeout by sending `TOUCH` back to nsqd. So this issue should be closed.
